name: videoplay
version: 0.2.1
author: Groboclown <matt@groboclown.net>
description: Embed video players in your webpage, and control them in Dart.
homepage: https://github.com/groboclown/videoplay.dart
environment:
  sdk: '>=1.6.0'
documentation: https://github.com/groboclown/videoplay.dart/tree/stable/doc
dev_dependencies:
  browser: '>=0.10.0+2'
